### ISSUE TITLE
Nav & Footer

### ISSUE THREAD

**Issue by mxstbr** [plotly/academy#1]
Could one of you send me the markup and the styling of your Nav and Footer? It'd be a waste of time and money to reimplement those if they already exist...

**Comment by chriddyp** [comment]
hey @mxstbr - check out our [documentation](https://github.com/plotly/documentation/tree/source) - this repo serves all the API documentation pages like plot.ly/python, plot.ly/javascript. here is the header and footer that we use: https://github.com/plotly/documentation/blob/source/_includes/header.html, https://github.com/plotly/documentation/blob/source/_includes/footer.html

**Comment by mxstbr** [comment]
:+1: Nice, thanks!
