### ISSUE TITLE
Typo and future folder maybe?

### ISSUE THREAD

**Issue by iDams** [plotly/academy#12]
> We learned how to structure our application, with a common components/ folder.

There is no `components/` folder in our app at this point of the tutorial.

> We’re not taking of rendering an error message

A little typo error: taLking :)

Let me know if you think I am going to deeply in feedbacks. 
For now, your tutorial is very clear and comprehensive!

**Comment by mxstbr** [comment]
No, this is great! The `components/` folder is in fact an artifact from before-create-react-app, will fix asap!
