### ISSUE TITLE
React with Plotly - Warnings

### ISSUE THREAD

**Issue by iDams** [plotly/academy#14]
Hey Max,

I have different warnings and an error in the Plotly.min.js:
<img width="1279" alt="screen shot 2016-08-05 at 12 00 32 pm" src="https://cloud.githubusercontent.com/assets/1591702/17433334/5bd704ae-5b04-11e6-87c4-94f5a5b44546.png">

Warnings are coming from eslint rules, I guess. Maybe we should not use the name `data` for the data we get from our xhr request and for the data we are going to use when we do `var data = JSON.parse(data.body);`. It might be confusing too for users.
For the Plotly undefined warning, we should declared Plotly as a global variable in an eslint config but eslint is not really a part of the tutorial so I am not sure what to do. Leave the warning or add a few lines in the tutorial about declaring Plotly as a global in eslint :)

EDIT: Forget about Plotly error, it was because I didn't specify data like `x`, `y`, `type`... in `Plotly.newPlot()`. My bad!

**Comment by mxstbr** [comment]
Ahhh good catch, also an artifact from moving to `create-react-app`!

> For the Plotly undefined warning, we should declared Plotly as a global variable in an eslint config but eslint is not really a part of the tutorial so I am not sure what to do.

Hmm, that's an annoying one! We could put a comment at the top of the file defining Plotly as a global?

**Comment by iDams** [comment]
Oh yeah!

I thought about this too:
```
/* eslint-disable no-undef */
    Plotly.newPlot('plot', [{
      x: this.props.xData,
      y: this.props.yData,
      type: this.props.type
    }], {
      margin: {
        t: 0, r: 0, l: 30
      },
      xaxis: {
        gridcolor: 'transparent'
      }
    }, {
      displayModeBar: false
    });
    /* eslint-enable no-undef */
```

But since we are not talking about eslint at all in the tutorial, your solution is better :)

**Comment by mxstbr** [comment]
Yeah I think telling people to write this at the top of Plot.js is nicer and easier to explain:

```JS
/* global Plotly */
```

**Comment by mxstbr** [comment]
Both fixed now! 🎉 no more warnings!
