### ISSUE TITLE
[Frontend Tutorial] Links open in same window

### ISSUE THREAD

**Issue by wallace80** [plotly/academy#18]
Links open in the same window as the tutorial. You have to sign up / copy the key / read the documentation and then hit back a bunch of times to continue where you were. 
For the sake of the tutorial flow it might be a good idea to open the links in new windos/tabs

**Comment by mxstbr** [comment]
Yess, good catch! I moved the ones in chapter one over to new tab today, will do the rest tomorrow! (PR maybe?)

**Comment by wallace80** [comment]
Can't do a PR today, maybe tomorrow.

**Comment by mxstbr** [comment]
All fixed, thanks!
