### ISSUE TITLE
[Frontend Tutorial] Chapter 4 File Name Confuision

### ISSUE THREAD

**Issue by wallace80** [plotly/academy#20]
In chapter 4 of the tutorial when adding redux the file names seem mixed up. In the structure defined from create-react-app there is no _app.js_ but index.js. There is also no folder _components_

**Comment by mxstbr** [comment]
Good catch, that's an artifact! PR maybe? Otherwise I'll fix it soon!

**Comment by wallace80** [comment]
Can't do a PR today, maybe tomorrow.
