### ISSUE TITLE
[Frontend Tutorial] Chapter 4 ReactDOM.render missing RootNode

### ISSUE THREAD

**Issue by wallace80** [plotly/academy#21]
In the code snipped when adding the provider in _index.js_:

`
ReactDOM.render(
    <Provider store={store}>
        <App />
    </Provider>
);
`

it should be

`
ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
);
`

**Comment by mxstbr** [comment]
:+1: PR maybe?

**Comment by wallace80** [comment]
Can't do a PR today, maybe tomorrow.

**Comment by mxstbr** [comment]
Fixed, thanks so much for all the bug reports!
