### ISSUE TITLE
[Chapter 3] - Good practice 2?

### ISSUE THREAD

**Issue by iDams** [plotly/academy#27]
We set a `click` event on the `plot` element like this `document.getElementById('plot').on('plotly_click', this.props.onPlotClick);`

Not sure but should we remove it in `componentWillUnmount()`? Not sure how `on('click')` works.
I usually use `addEventListener()` in `componentDidMount()` and `removeEventListener()` in `componentWillUnmout()`. Should we do the same here?

Asking for my personal knowledge and good practice :)

**Comment by mxstbr** [comment]
Sounds like a good idea!

**Comment by mxstbr** [comment]
Turns out, `on` is a plotly specific API and they take care of that. See the [plotly documentation](https://plot.ly/javascript/plotlyjs-function-reference/#plotly-redraw)!

Thanks for figuring this out!
