### ISSUE TITLE
Tagline

### ISSUE THREAD

**Issue by mxstbr** [plotly/academy#4]
Any ideas for a tagline for Plotly Academy?

**Comment by chriddyp** [comment]
maybe something along the lines of:
> Tutorials and workshops on the open-source stack that powers Plotly

On Wed, Jan 13, 2016 at 7:34 AM, Max Stoiber <notifications@github.com>
wrote:

> Any ideas for a tagline for Plotly Academy?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/academy/issues/4>.
>



-- 
Chris Parmer
Plotly, Chief Product Officer
514 571 5897
https://plot.ly/team

**Comment by mxstbr** [comment]
>  Tutorials and workshops on the open-source stack that powers Plotly

@jackparmer suggested the following via mail:

> Skills and techniques used by engineering @plotlygraphs

I like "Tutorials and workshops" more, "Skills and techniques" sounds a bit like a list of things you use. What about this:

> Tutorials and workshops on the open-source stack used @plotlygraphs

**Comment by chriddyp** [comment]
+1 "Tutorials and workshops on the open-source stack used by @plotlygraphs"

On Wed, Jan 13, 2016 at 12:52 PM, Max Stoiber <notifications@github.com>
wrote:

> Tutorials and workshops on the open-source stack that powers Plotly
>
> @jackparmer <https://github.com/jackparmer> suggested the following via
> mail:
>
> Skills and techniques used by engineering @plotlygraphs
>
> I like "Tutorials and workshops" more, "Skills and techniques" sounds a
> bit like a list of things you use. What about this:
>
> Tutorials and workshops on the open-source stack used @plotlygraphs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/academy/issues/4#issuecomment-171378514>.
>



-- 
Chris Parmer
Plotly, Chief Product Officer
514 571 5897
https://plot.ly/team
