### ISSUE TITLE
[Introduction] - Browserify part - no require error as it should be

### ISSUE THREAD

**Issue by iDams** [plotly/academy#6]
Hey,

In the Browserify section, when I open the `index.html` file without transpiling the `main.js`, I have no error like you say:

> If you try opening the index.html file in your browser now, you’ll see an error in your console saying something like “require is undefined”.

`main.js` is loaded but not executed apparently.
You need to add it like this in the `index.html`:
`<script src="./main.js"></script>` **instead of this** `<script src="./main.js" />` 

EDIT: same thing when you add `bundle.js` :)

**Comment by mxstbr** [comment]
That's what I get for thinking I know HTML! Thanks so much, fixed.

I've also just completely revamped the first part with ES6 syntax because I switched to using that later on!

**Comment by iDams** [comment]
ES6 <3
